[pytest]
pythonpath =
  packages/deepfix-core/src
  packages/deepfix-sdk/src
  packages/deepfix-server/src
  packages/deepfix-portal/src
  packages/deepfix-kb/src
testpaths =
  packages/deepfix-core/tests
  packages/deepfix-sdk/tests
  packages/deepfix-server/tests
  packages/deepfix-portal/tests
  packages/deepfix-kb/tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
